"""saturday polished with join tables and write_privileges

Revision ID: 4c9bad91f00d
Revises: 3af956e111b4
Create Date: 2023-06-03 10:02:27.757800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9bad91f00d'
down_revision = '3af956e111b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_privileges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('write_privileges', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_privileges', schema=None) as batch_op:
        batch_op.drop_column('write_privileges')

    # ### end Alembic commands ###