"""saturday without join tables

Revision ID: 9fddcab581c6
Revises: f4c84a76ec65
Create Date: 2023-06-03 09:39:51.446021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fddcab581c6'
down_revision = 'f4c84a76ec65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share_privileges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_privileges',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('note_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'note_id')
    )
    # ### end Alembic commands ###